apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  selector:
    app: result
  ports:
    - protocol: TCP
      port: {{ .Values.result.service.port }}
      targetPort: {{ .Values.result.containerPort }}
  type: {{ .Values.result.service.type }}

