apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.result.port }}
      nodePort: {{ .Values.result.nodePort }}
  type: {{ .Values.result.service.type }}

