apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: {{ .Values.result.image }}
          imagePullPolicy: {{ .Values.result.pullPolicy }}
          ports:
            - containerPort: {{ .Values.result.containerPort }}
