apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: {{ .Values.vote.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: {{ .Values.vote.image }}
          imagePullPolicy: {{ .Values.vote.pullPolicy }}
          ports:
            - containerPort: {{ .Values.vote.port }}
