apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.containerPort }}
      nodePort: {{ .Values.vote.nodePort }}
  type: {{ .Values.vote.service.type }}
